# Generated by Django 4.2.2 on 2023-08-03 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0006_suggestion_business_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestion',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='suggestion',
            name='expected_revenue',
        ),
    ]
