# Generated by Django 4.2.2 on 2023-08-03 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0007_remove_suggestion_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='depreciation_year1',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='depreciation_year2',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='depreciation_year3',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='fixed_asset_investment_year1',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='fixed_asset_investment_year2',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='fixed_asset_investment_year3',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='non_fixed_asset_investment_year1',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='non_fixed_asset_investment_year2',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='non_fixed_asset_investment_year3',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='other_expenses_year1',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='other_expenses_year2',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='other_expenses_year3',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='revenue_year1',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='revenue_year2',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='revenue_year3',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='yield_rate',
            field=models.DecimalField(blank=True, decimal_places=1, default=1.0, max_digits=3, null=True),
        ),
    ]
